# General Options
logic_filename:       router_logic.txt
nodes_filename:       router_nodes.txt
retry_limit:           750  # Max loops before reaching goal
retry_limit_close:    1000  # Max loops to cleanup once goal has been reached
time_limit:            600  # Seconds before giving up
fg_cache_limit:      10000  # Max cache size for node guarantee simplification
map_size:             0.75  # Percentage of all possible nodes to connect
map_strictness:       0.75  # Lower bound portion of selected nodes to connect
avoid_softlocks:      True  # Create a graph where you can't get stuck
skip_complex_nodes:   0.50  # Rate to skip nodes that are difficult to route
lazy_complex_nodes:   False # Simplify complex nodes (softlock potential)
goal_based_missables: True  # Missable nodes only relevant if required by goal
no_logic:             False # Disable maze routing logic

# MN64 Specific Options
fix_bad_maps:         True  # Alter specific maps to remove softlock potential
fixed_singletons:     1.00  # Rate to preserve connections to isolated rooms
cluster_bgm:          True  # Try to connect rooms with the same BGM
completionist:        False # Guarantee all key items are accessible
all_warps:            False # Guarantee all inns and teahouses are accessible
randomize_keys:       2     # Generate keys and locked doors, 1-3 recommended
randomize_pickups:    True  # Randomize pickups such as dangos and cat dolls
randomize_enemies:    True  # Randomize enemies (may cause softlocks & crashes)
enable_debug:         True  # Enable debug menu by pressing L
start_camera:         False # Start with Ebisumaru's Karakuri Camera
start_minimaru:       False # Start with Mini-Ebisu magic already learned
start_flute:          True  # Start with Yae & Flute
start_mermaid:        False # Start with Mermaid magic already learned
flute_anywhere:       True  # Flute works anywhere
start_snow:           True  # Start with Miracle Snow
ice_kunai_logic:      True  # Incorporate Ice Kunai into logic
ryo_hover_logic:      False # Incorporate Ryo Hover into logic (experimental)
jp_super_jump_logic:  False # Incorporate better super jump on JP version
sasuke_mode:          True  # Start as Sasuke & Yae instead of Goemon & Ebi
hard_mode:            False # Take 4x damage from all sources
automash:             False # Eliminate button mashing during long cutscenes
