# General Options
logic_filename:       router_logic.txt
nodes_filename:       router_nodes.txt
retry_limit:           500  # Max loops before reaching goal
retry_limit_close:    1000  # Max loops to cleanup once goal has been reached
time_limit:            240  # Seconds before giving up
map_size:             0.75  # Percentage of all possible nodes to connect
map_strictness:       0.75  # Lower bound portion of selected nodes to connect
skip_complex_nodes:   0.50  # Rate to skip nodes that are difficult to route
lazy_complex_nodes:   False # Simplify complex nodes (softlock potential)
avoid_softlocks:      True  # Create a graph where you can't get stuck
trap_doors:           0.00  # Rate to allow one-way trick doors

# MN64 Specific Options
fix_bad_maps:         True  # Alter specific maps to remove softlock potential
fixed_singletons:     1.00  # Rate to preserve connections to isolated rooms
cluster_bgm:          True  # Try to connect rooms with the same BGM
randomize_keys:       3     # Generate keys and locked doors, 1-3 recommended
randomize_pickups:    True  # Randomize pickups such as dangos and cat dolls
randomize_enemies:    False # Randomize enemies (may cause softlocks & crashes)
enable_debug:         True  # Enable debug menu by pressing L
start_camera:         False # Start with Ebisumaru's Karakuri Camera
start_minimaru:       False # Start with Mini-Ebisu magic already learned
start_flute:          False # Start with Yae & Flute
start_snow:           True  # Start with Miracle Snow
