seed:                 0
seed:                 8006929380
logic_filename:       router_logic.txt
nodes_filename:       router_nodes.txt
retry_limit:           500  # Max loops before reaching goal
retry_limit_close:    1000  # Max cleanup loops when goal has been reached
time_limit:            240  # Seconds before giving up
  #time_limit:            900  # Seconds before giving up
time_limit:             50  # Seconds before giving up
map_size:             0.75  # Percentage of all possible nodes to connect
  #map_size:             1.00  # Percentage of all possible nodes to connect
  #map_size:             0.10  # Percentage of all possible nodes to connect
map_strictness:       0.75  # Lower bound portion of selected nodes to connect
  #map_strictness:       0.95  # Lower bound portion of selected nodes to connect
  #trap_doors:           0.10  # Rate to allow one-way doors
  #skip_complex_nodes:   1.00  # Rate to skip nodes that are difficult to route
  #lazy_complex_nodes:   True  # Simplify complex nodes (softlock potential)
avoid_oneway_traps:   True
fixed_singletons:     1.00  # Rate to preserve connections to isolated rooms
cluster_bgm:          True  # Try to connect rooms with the same BGM
randomize_keys:       2     # Generate keys and locked doors, low # recommended
randomize_pickups:    True  # Randomize pickups such as dangos and cat dolls
start-flute:          True  # Start with Yae & Flute
start-snow:           True  # Start with Miracle Snow
