byte_order:                 "big"
opcode_size:                4
pointer_size:               3
virtual_address:            0
terminators:                [0x8008]
text_terminators:           [0xffff]
text_char_size:             2
text_decode_table:
  0xffb9: "{end}"
  0xffba: "{begin}"
  0xffc1: "{newwindow}"
  0xffc2: "{waitinput}"
  0xffc3: "{button}"
  0xffc4: "{newline}"
  0xffc7: "{/big}"
  0xffc8: "{big}"
  0xffcd: "{/blink}"
  0xffce: "{blink}"
  0xffdb: "{unknown-ffdb}"
  0xffdc: "{em-green}"
  0xffdd: "{em-blue}"
  0xffde: "{em-red}"
  0xffdf: "{em-yellow}"
  0xffe0: "{/em}"
  0xffff: "{endline}"
instructions:
  0x8002:
    comment:                "Skip Next If Not Equal: {value:x}"
    parameters:
      value:
        length:             4
  0x8003:
    comment:                "Skip Next If Equal: {value:x}"
    parameters:
      value:
        length:             4
  0x8004:
    comment:                "Write to RAM {address:x} ({_pretty_address})"
    parameters:
      address:
        length:             4
        prettify:
          -1:               "Unknown"
  0x8006:
    comment:                "Read from RAM {address:x} ({_pretty_address})"
    parameters:
      address:
        length:             4
        prettify:
          -1:               "Unknown"
  0x8008:
    comment:                "End Event"
  0x8009:
    comment:                "Store Value: {value:x}"
    parameters:
      value:
        length:             4
  0x800a:
    comment:                "Jump To {address:x}"
    parameter_order:        ['prefix', 'address']
    parameters:
      prefix:
        length:             1
      address:
        length:             3
        track_pointer:      True
        virtual_address:    0
  0x800b:
    comment:                "Execute Code: {address:x} ({_pretty_address})"
    parameters:
      address:
        length:             4
        prettify:
          -1:               "Unknown"
  0x800c:
    comment:                "Skip Next If Not Less Than {value:x}"
    parameters:
      value:
        length:             4
  0x8010:
    comment:                "Print Text"
    parameter_order:        ['prefix', 'text']
    parameters:
      prefix:
        length:             1
      text:
        length:             3
        track_pointer:      True
        virtual_address:    0
        is_text:            True
  0x8011:
    comment:                "Begin Option Selection"
  0x8012:
    comment:                "End Option Selection"
  0x8013:
    comment:                "Increase By {value:x}"
    parameters:
      value:
        length:             4
  0x8015:
    comment:                "Unknown 8015 (Related to saving)"
    parameters:
      address:
        length:             4
  0x8017:
    comment:                "Unknown 8017 (Related to saving)"
    parameters:
      value:
        length:             4
  0x8020:
    comment:                "Set Flag {flag:0>3x}"
    parameters:
      flag:
        length:             4
  0x8021:
    comment:                "Unset Flag {flag:0>3x}"
    parameters:
      flag:
        length:             4
  0x8022:
    comment:                "If Flag {flag:0>3x}, Jump To {address:x}"
    parameter_order:        ['flag', 'prefix', 'address']
    parameters:
      flag:
        length:             4
      prefix:
        length:             1
      address:
        length:             3
        track_pointer:      True
        virtual_address:    0
  0x8030:
    comment:                "Skip Next If {address:x} ({_pretty_address}) Not Equal"
    parameters:
      address:
        length:             4
        prettify:
          -1:               "Unknown"
